substitutions:
  # This depends on how your device is wired.
  PIN_LED: GPIO08
  PIN_BUTTON: GPIO09
  # Insert your own keys here.
  API_KEY: "COPY_FROM_GENERATED_CODE"
  OTA_KEY: "COPY_FROM_GENERATED_CODE"

esphome:
  name: workshop-${OTA_KEY[-6:]}
  friendly_name: Workshop Demo

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: ${API_KEY}

ota:
  - platform: esphome
    password: ${OTA_PASSWORD}

wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: "changeme"

# captive_portal:

binary_sensor:
  - id: boot_button
    name: Boot Button
    platform: gpio
    pin:
      number: ${PIN_BUTTON}
      inverted: True

light:
  - id: led
    name: Board LED
    platform: monochromatic
    output: led_output
    effects:
      - pulse:
      - flicker:
          intensity: 50%
      - strobe:

output:
  - id: led_output
    platform: ledc
    pin:
      number: ${PIN_LED}
      inverted: True

web_server:
  version: 3
  local: true
