# GPIO Output

esphome:
  name: workshop-demo
  on_boot:
    - logger.log: Hello World
    - while:
        condition: {and: []}  # While true
        then:
          - logger.log: "*blink*"
          - output.turn_on: led
          - delay: 0.5s
          - output.turn_off: led
          - delay: 1s

output:
  - id: led
    platform: gpio
    pin:
      number: GPIO08
      inverted: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
