# Light Component

esphome:
  name: workshop-demo
  on_boot:
    then:
      - logger.log: Hello World

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

output:
  - id: led_output
    platform: ledc
    pin:
      number: GPIO08
      inverted: true

light:
  - id: led
    platform: monochromatic
    output: led_output
    restore_mode: RESTORE_DEFAULT_OFF

preferences:
  # DON'T USE THIS IN PRODUCTION, it is just for the demo
  flash_write_interval: 5s

binary_sensor:
  - id: boot_button
    platform: gpio
    name: Boot Button
    pin:
      number: GPIO09
      inverted: true
    on_click:
      - light.turn_on:
          id: led
          brightness: !lambda |-
            // Cycle through 4 levels of brightness
            const int LEVELS = 4;
            int current_level_idx = round(id(led).current_values.get_brightness() * (LEVELS-1));
            if (!id(led).current_values.is_on()) {
              current_level_idx = 0;
            }
            int new_level_idx = (current_level_idx + 1) % LEVELS;
            return float(new_level_idx) / (LEVELS-1);
